// LAST GAME IS dungeons and degenerate gamble
let files = [
  "cl64in1nes",
  "cl90in1nes",
  "clacecombat2",
  "clacecombat3",
  "cladvancewars",
  "cladvancewars2",
  "cladvancewarsdualstrike",
  "claladdinsnes",
  "clalexkiddinmiracleworld",
  "clalienhominidgba",
  "clAltered Beast",
  "clanimalcrossingwildworld",
  "clanimalforestn64",
  "clannsmb",
  "clastynax",
  "clatariadventure",
  "claxbattler",
  "clbalatrogba",
  "clbananasimulator",
  "clbanjokazooie",
  "clbanjotooie",
  "clbackyardbaseball",
  "clbackyardbaseball09",
  "clbackyardbaseball10",
  "clbackyardfootball",
  "clbackyardsoccer",
  "clbejeweledtwistds",
  "clben10alienforce",
  "clben10omniverse",
  "clben10protector",
  "clben10racing",
  "clben10ultimatealien",
  "clbomberman",
  "clbomberman2",
  "clbombermanhero",
  "clbombermanworld",
  "clBonanza-Bros",
  "clbonkerssnes",
  "clbotwds",
  "clbushidoblade",
  "clcannonfodder",
  "clcaptainlang",
  "clcastlecircleofmoon",
  "clcastlevania",
  "clcastlevania2",
  "clcastlevania3",
  "clcastlevaniaariaofsorrow",
  "clcastlevaniadawnofsorrow",
  "clcastlevanianes",
  "clchainofmemories",
  "clchoroqwonderful",
  "clchronotrigger",
  "clcod4",
  "clcodblackopp",
  "clcoddefiance",
  "clcodmodernwarfare",
  "clcodworldatwar",
  "clconkersbadfurday",
  "clcontra",
  "clcontra3",
  "clcookingmama",
  "clcookingmama2",
  "clcookingmama3",
  "clcoryinthehouse",
  "clcrash2",
  "clcrash3",
  "clcrashbandicoot (1)",
  "clcrashbandicoot",
  "clcrashbandicoot2",
  "clcrashteamracing",
  "clcrazyfrogracer",
  "clcrazytaxigba",
  "cldaggerfall",
  "cldborigins",
  "cldborigins2",
  "cldbzattacksaiyans",
  "cldbzwarriors2",
  "cldeblob2",
  "cldementium",
  "cldiddykong-racing",
  "cldinodudes",
  "cldkccompetitioncart",
  "clDKNESCollection(1)",
  "clDKNESCollection",
  "cldonkeykong",
  "cldonkeykong64",
  "cldonkeykong94",
  "cldonkeykongcountry",
  "cldonkeykongcountry2",
  "cldonkeykongcountry3",
  "cldonkeykongnes",
  "cldoom64",
  "cldoubledribble",
  "cldragonballadvance",
  "clDragonBallZTheLegacyofGoku",
  "cldragonquest5ds",
  "clDragonQuestIX",
  "cldragonwarriormonsters",
  "cldrawntolife",
  "cldrawntolife2",
  "cldrmario",
  "clducktales",
  "clducktales2",
  "cldukenukem2",
  "cldukenukem3d",
  "cldynamiteheaddy",
  "clearthbound",
  "clearthbound3",
  "clearthboundsnes",
  "clearthwormjim (1)",
  "clearthwormjim",
  "clearthwormjim2 (1)",
  "clearthwormjim2",
  "clelevatoraction",
  "clenduro",
  "clet",
  "cletrianoddyssey",
  "clexcitebike64",
  "clfantasyzone",
  "clff2ws",
  "clFF3",
  "clff6",
  "clffaf",
  "clffmysticquest",
  "clFIFA07",
  "clFIFA10",
  "clFIFA11",
  "clFIFA2000(1)",
  "clFIFA2000(2)",
  "clfifa2000",
  "clFIFA99",
  "clFIFAinternationalsoccer",
  "clFIFAroadtoworldcup98",
  "clFIFAsoccer06",
  "clFIFAsoccer95",
  "clFIFAsoccer96",
  "clFIFAsoccer97",
  "clFIFAstreet2",
  "clfinalfantasy",
  "clfinalfantasy2nes",
  "clfinalfantasy3nes",
  "clfinalfantasyII",
  "clfinalfantasyIX",
  "clfinalfantasylegend2",
  "clfinalfantasytactics",
  "clfinalfantasyVI",
  "clfinalfantasyVII",
  "clfireemblem",
  "clfzero",
  "clfzerox",
  "clgeneralchaos",
  "clggshinobi",
  "clggshinobi2",
  "clghosttrick",
  "clglover",
  "clgoldenaxe",
  "clgoldenaxe2",
  "clgoldenaxe3",
  "clgoldeneye007",
  "clgoldensun",
  "clgoldensunnds",
  "clGoldenSunTheLostAge",
  "clgooftroopsnes",
  "clgrandtheftautoadvance",
  "clgranturismo",
  "clgranturismo2",
  "clgta",
  "clgta2",
  "clgta22",
  "clgunsmoke",
  "clgunstarheroes",
  "clgyromite",
  "clhajimeippo",
  "clhajimenoippo",
  "clhangonsms",
  "clharmonyofdissonance",
  "clharvestmoon",
  "clharvestmoon2",
  "clharvestmoon64",
  "clinsidestory",
  "clironsoldier",
  "cljamesbondjr",
  "cljazzjackrabbit",
  "cljazzjackrabbit2",
  "cljetforcegemini",
  "cljojobaps1",
  "cljunglebooksnes",
  "cljurassicpark",
  "clkaizomarioworld",
  "clKenGriffeyJrPresentsMajorLeagueBaseball",
  "clkillerinstinct",
  "clkingdomheartsdays",
  "clkingdomheartsrecoded",
  "clkirby64",
  "clkirby64crystalshards",
  "clkirbyandtheamzingmirror",
  "clkirbycanvascurse",
  "clkirbysadventure",
  "clkirbysdreamland",
  "clkirbysdreamland3",
  "clkirbysqueaksquad",
  "clkirbysuperstar",
  "clkirbysuperstarultra",
  "clkirbytiltandtumble",
  "clLegacyOfGoku",
  "cllegobatman",
  "cllegobatman2superheroes",
  "cllegoindianajones",
  "cllegoindianajones2",
  "cllegoninjago",
  "cllegostarwars",
  "cllegostarwars2gba",
  "cllegostarwarsgba",
  "cllemmings",
  "clletsgopikachu",
  "clletsgoeevee",
  "cllinerider",
  "cllinksawakeningdx",
  "cllinktothepast",
  "clloderunner",
  "clloz1",
  "cllozlinkawakening",
  "cllozminishcap",
  "cllozoracleofseasons",
  "cllozphantomhourglass",
  "cllozspirittracks",
  "clmadden93",
  "clmadden94",
  "clmadden95",
  "clmadden96",
  "clmadden99",
  "clmaddenfootball",
  "clmaddenfootball64",
  "clmaddennfl",
  "clmaddennfl2000",
  "clmaddennfl2001",
  "clmaddennfl2002",
  "clmaddy98",
  "clmajorasmask",
  "clmario3",
  "clmarioandluigisuperstarsaga",
  "clmariogolf",
  "clmariokart64",
  "clmariokartds",
  "clmariokartsupercircuit",
  "clmariolostlevels",
  "clmariomakersnes",
  "clmariominusrabbids",
  "clmariopaint",
  "clmarioparty",
  "clmarioparty2",
  "clmarioparty3",
  "clmariopartyds",
  "clmariotennis",
  "clmariotennisgb",
  "clmariovsluigi",
  "clMarvelVsCapcomPS1",
  "clmauimallard",
  "clmaxpayne",
  "clmcraerally",
  "clmedalofhonor",
  "clmedievil",
  "clmegacd",
  "clmegaman",
  "clmegaman2",
  "clmegaman2gba",
  "clmegaman3",
  "clmegaman4",
  "clmegaman5",
  "clmegaman5gb",
  "clmegaman6",
  "clmegaman7",
  "clmegaman8",
  "clmegamanbasscftf",
  "clmegamanbattlechipchallenge",
  "clmegamanbn5tc",
  "clmegamanbn5tp",
  "clmegamanbn6cf",
  "clmegamanbn6cg",
  "clmegamanlegends",
  "clmegamanlegends2",
  "clmegamanx",
  "clmegamanx2",
  "clmegamanx3",
  "clmegamanx4",
  "clmegamanx5",
  "clmegamanx6",
  "clmegamanzero",
  "clmegamanzx",
  "clmetalgear",
  "clmetalgearsolid",
  "clmetalgearsolidps",
  "clmetalslug",
  "clmetalslug2",
  "clmetalslugadvance",
  "clmetroid",
  "clmetroid2",
  "clmetroidfusion",
  "clmetroidprimehunters",
  "clmetroidzeromission",
  "clmickeymaniasnes",
  "clmicromages",
  "clmidwaysgreatesthitsn64",
  "clminecraftpocketedition",
  "clmk4ampedup",
  "clmkmythologiesn64",
  "clmktrilogyps1",
  "clmmbn3b",
  "clmmbn3w",
  "clmmbn4bm",
  "clmmbn4rs",
  "clmmbnws",
  "clmmsf2zxn",
  "clmmsf2zxs",
  "clmmsf3ba",
  "clmmsf3rj",
  "clmmsfd",
  "clmmsfl",
  "clmmsfp",
  "clmmwilywars",
  "clmortalkombat",
  "clmortalkombat2",
  "clmortalkombat2a",
  "clmortalkombat3",
  "clmortalkombat3a",
  "clmortalkombat4",
  "clmortalkombata",
  "clmortalkombatadvance",
  "clmortkom4",
  "clmotoroadrash",
  "clmultitask",
  "clmvpbaseball",
  "clnarc",
  "clNBAhangtime",
  "clNBAjam",
  "clnbajamTE",
  "clnbalive2000",
  "clnbalive2003",
  "clnewersmbds",
  "clnewsupermariobros",
  "clnfscarbonowncity",
  "clnfsmostwanted",
  "clnfsporcheunleashed",
  "clnfsunderground",
  "clnfsunderground2",
  "clnhl2002",
  "clnhl98",
  "clnhlhitz2003",
  "clNicktoonsFreezeFrameFrenzy",
  "clnightfire",
  "clnightshade",
  "clnintendogslab",
  "clnintendoworldcup",
  "clnsmbuds",
  "clnsmbwds",
  "clocarinaoftime",
  "clorigamiking",
  "cloutrungenesis",
  "clpacmanworld3",
  "clpacmanworldg",
  "clpacmanworldpsx",
  "clpapermario",
  "clpapermariottyd",
  "clparappatherapper",
  "clparappatherapperalt",
  "clpartnersintime",
  "clpeggle",
  "clpepsiman",
  "clpepsimanalt",
  "clperfectdark",
  "clpersona",
  "clpersona2",
  "clpersona2alt",
  "clpersonaalt",
  "clphantasystar",
  "clphantasystar2",
  "clphantasystar3",
  "clphantasystar4",
  "clpheonixjusticeforall",
  "clpheonixrightaceattorny",
  "clpicodriller",
  "clpitfall",
  "clplantsvszombiesnds",
  "clpokeblack",
  "clpokeblue",
  "clpokeclassic",
  "clpokediamond",
  "clpokeheartgold",
  "clpokemoncrystal",
  "clpokemonemerald",
  "clpokemonemeraldmini",
  "clpokemonfire-red",
  "clpokemonfirered",
  "clpokemongold",
  "clpokemonleafgreen",
  "clpokemonplatinum",
  "clpokemonred",
  "clpokemonruby",
  "clpokemonsapphire",
  "clpokemonsilver",
  "clpokemonsoulsilver",
  "clpokemonwhite",
  "clpokemonwhite2",
  "clpokemonxy",
  "clpokemonyellow",
  "clpopeye",
  "clpowerpuffgirlsGBA",
  "clPrimalRage",
  "clproevolutionsoccer2002",
  "clpunchout",
  "clquake",
  "clquake2",
  "clrayman",
  "clrayman2",
  "clrayman3gba",
  "clraymanadvance",
  "clraymanhoodlumhavoc",
  "clresidentevil2",
  "clresidentevil3",
  "clresidentevilgaiden",
  "clresidentevilpsx",
  "clroadrash",
  "clroadrash2",
  "clroadrash3",
  "clroadrash64",
  "clsamuraishodown",
  "clshrek2gba",
  "clsilenthill",
  "clsimpsonsbartvsspacemutants",
  "clsimpsonsnes",
  "clsonic1",
  "clsonic2",
  "clsonic3",
  "clsonicadvance",
  "clsonicadvance2",
  "clsonicadvance3",
  "clsonicandknuckles",
  "clsonicbattle",
  "clsoniccd",
  "clsonicpinball",
  "clsonicrush",
  "clspidermanps1",
  "clspidermanwos",
  "clspyro",
  "clspyro2",
  "clspyro3",
  "clspyrogba",
  "clstreetfighter2",
  "clstreetsofrage",
  "clstreetsofrage2",
  "clstreetsofrage3",
  "clsupermario64",
  "clsupermarioallstars",
  "clsupermariobros",
  "clsupermariobros2",
  "clsupermariobros3",
  "clsupermariobrosnes",
  "clsupermarioland",
  "clsupermarioland2",
  "clsupermarioworld",
  "clsupermarioworld2",
  "clsupermetroid",
  "clsupersmashbros",
  "cltekken",
  "cltekken2",
  "cltekken3",
  "cltetris",
  "cltetrisnes",
  "cltmnt",
  "cltmntnes",
  "cltonyhawk",
  "cltonyhawk2",
  "cltonyhawk3",
  "cltonyhawk4",
  "cltoystory2",
  "cltwistedmetal",
  "cltwistedmetal2",
  "clwario-land4",
  "clwarioland4",
  "clwariowarediy",
  "clwariowareinc",
  "clwariowaretouched",
  "clwwenofmercy",
  "clwwe smackdown",
  "clzelda1",
  "clzelda2",
  "clzeldalinktothepast",
  "clzeldaminishcap",
  "clzeldaocarinaoftime"
  ];

   const filesByChar = {};
  allChars.forEach((char) => {
    filesByChar[char] = [];
  });

  files.forEach((file) => {
    const lower = file.toLowerCase();
    if (lower.startsWith("cl")) {
      const aftercl = lower.substring(2);
      if (aftercl.length > 0) {
        const firstChar = aftercl[0].toUpperCase();
        if (filesByChar[firstChar]) {
          filesByChar[firstChar].push(file);
        }
      }
    }
  });

  const container = document.getElementById("sections-container");
  allChars.forEach((char) => {
    const section = document.createElement("div");
    section.className = "letter-section";
    section.id = `section-${char}`;

    const header = document.createElement("div");
    header.className = "letter-header";
    header.textContent = char;
    section.appendChild(header);

    const buttonsContainer = document.createElement("div");
    buttonsContainer.className = "buttons-container";

    if (filesByChar[char].length > 0) {
      filesByChar[char].forEach((file) => {
        const btn = document.createElement("input");
        btn.type = "button";
        btn.value = file;
        btn.onclick = () => {
          function normalizeFileName(name) {
            if (name.includes(".") && name.lastIndexOf(".") > 0) return name;
            return name + ".html";
          }

          const normalized = normalizeFileName(file);
          const encoded = encodeURIComponent(normalized);

          fetch(
            `https://cdn.jsdelivr.net/gh/bubbls/ugs-singlefile/UGS-Files/${encoded}?t=${Date.now()}`,
          )
            .then((response) => response.text())
            .then((text) => {
              const newWin = window.open("about:blank", "_blank");
              if (newWin) {
                newWin.document.open();
                newWin.document.write(text);
                newWin.document.close();
              }
            });
        };
        btn.style.width = "100%";
        btn.style.height = "100%";
        buttonsContainer.appendChild(btn);
      });
    } else {
      section.classList.add("empty");
      const emptyMsg = document.createElement("div");
      emptyMsg.className = "empty-message";
      emptyMsg.textContent = "No files";
      buttonsContainer.appendChild(emptyMsg);
    }

    section.appendChild(buttonsContainer);
    container.appendChild(section);
  });

  generateSidebar(allChars, filesByChar);
}

function generateSidebar(allChars, filesByChar) {
  const sidebar = document.getElementById("sidebar");

  allChars.forEach((char) => {
    const btn = document.createElement("button");
    btn.className = "sidebar-btn";
    btn.textContent = char;

    if (filesByChar[char].length === 0) {
      btn.classList.add("empty");
    } else {
      btn.onclick = () => {
        const section = document.getElementById(`section-${char}`);
        if (section) {
          section.scrollIntoView({
            behavior: "smooth",
            block: "start",
          });
        }
      };
    }

    sidebar.appendChild(btn);
  });
}
generateAllSections();